#!/bin/sh

cvsclean=0
rebuild=0

while test $# -gt 0; do
  if test "$1" = "--force"; then
    rebuild=1
    echo "Forcing buildconf"
  fi
  if test "$1" = "--clean"; then
    cvsclean=1
  fi
  shift
done

if test "$cvsclean" = "1"; then
	echo "Cleaning autogenerated files"
	${MAKE:-make} -s -f build.mk cvsclean
else 
	${MAKE:-make} -s -f build.mk
fi

