/* This file is autogenerated, edit the original template instead! */

/* Copyright (c) 2007-2009 Antony Dovgal <tony@daylessday.org>

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; version 2 of the License.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
void pinba_update_report_info_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report_info_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report1_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report1_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report2_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report2_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report3_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report3_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report4_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report4_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report5_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report5_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report6_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report6_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report7_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report7_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report8_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report8_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report9_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report9_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report10_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report10_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report11_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report11_delete(pinba_report *report, const pinba_stats_record *record);

void pinba_update_report12_add(pinba_report *report, const pinba_stats_record *record);
void pinba_update_report12_delete(pinba_report *report, const pinba_stats_record *record);

